[package]
name = "http_serv_to_kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
envy = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
